// <auto-generated>
// Rewired Constants
// This list was generated on 3/12/2021 9:53:31 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Open Radial (Hold)")]
        public const int OpenRadial = 18;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Select Radial Item")]
        public const int Select = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Back (Radial Menu)")]
        public const int BackRadial = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Unlock Unit Tower")]
        public const int Unlock = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Build Expansion")]
        public const int Upgrade = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Open Pause Menu")]
        public const int Start = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Rotate Tower Left")]
        public const int RotateTowerLeft = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Rotate Tower Right")]
        public const int RotateTowerRight = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveHorizontal")]
        public const int MoveHorizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "MoveVertical")]
        public const int MoveVertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Custom Game Options")]
        public const int CustomGameOptions = 21;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Return Settings to Defaults")]
        public const int DefaultSettings = 26;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "GodDetails")]
        public const int GodDetails = 20;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "View Previous Match Stats")]
        public const int PreviousMatchStats = 27;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "View Next Match Stats")]
        public const int NextMatchStats = 28;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "DPadUp")]
        public const int DPadUp = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "DPadDown")]
        public const int DPadDown = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "DPadLeft")]
        public const int DPadLeft = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "DPadRight")]
        public const int DPadRight = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LTriggerUI")]
        public const int LTriggerUI = 31;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LTriggerUI")]
        public const int LBumperUI = 33;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "RTriggerUI")]
        public const int RTriggerUI = 32;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "RBumperUI")]
        public const int RBumperUI = 34;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action1")]
        public const int UIHorizon = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int UIVert = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int UIConfirm = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int UIBack = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "LClick")]
        public const int LClick = 19;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Change Camera Zoom")]
        public const int Zoom_Camera = 29;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Disable Player UI")]
        public const int DisableUI = 30;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
            public const int Hot_Key = 2;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 1;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
